apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: gateway3-public
  namespace: proyecto
spec:
  rules:
    - host: nodejs.siguago.tk
      http:
        paths:
          - backend:
              serviceName: miapp-nodejs-srv
              servicePort: 3000
            path: /